---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  annotations: {}
  name: "nginx"
  labels:
    nirmata.io/deployment.name: "nginx"
    nirmata.io/application.name: "nginx"
    nirmata.io/component: "nginx"
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      nirmata.io/component: "nginx"
    matchExpressions: []
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations: {}
      labels:
        nirmata.io/deployment.name: "nginx"
        nirmata.io/component: "nginx"
    spec:
      hostNetwork: false
      terminationGracePeriodSeconds: 30
      nodeSelector: {}
      containers:
      - name: "nginx"
        image: "ghcr.io/nirmata/nginx:1.11.3-alpine"
        command: []
        args: []
        ports:
        - containerPort: 80
          protocol: "TCP"
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      securityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true

