name: PR-scan

on:
  pull_request:
    branches:
    - main

concurrency:
  group: ci-build-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  scan-manifests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout manifests
        uses: actions/checkout@v2

      - name: Download policies
        uses: actions/checkout@v2
        with:
          repository: nirmata/cci-policies
          path: './policies'

      - name: Install Nirmata CLI
        run: |
          curl -O -L -s https://nirmata-downloads.s3.us-east-2.amazonaws.com/nctl/nctl_3.3.7/nctl_3.3.7_linux_64-bit.zip
          unzip *.zip

      - name: Check nctl install
        run: ./nctl version

      - name: Validate manifests
        run: |
          ./nctl scan --policies ./policies/cci-policies/policies --resource=./nginx
